Aboutme
bronnie313/Portfolio pull request #3
Opened 2023-01-18 06:39 UTC by bronnie313

New pull request for the about part
added the about feature and also edited the works section
added styling to the page 
corrected the stylelint errors that I was getting

2023-01-18 07:43 UTC, TuyishimireEric requested changes
# Status: REQUIRED CHANGES :recycle: 
### Hi  @bronnie313   👋 👋 
#### I'm @TuyishimireEric, Your code reviewer,
Good job so far 👍 
 there are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

## Highlights 
✔ No Linter errors
✔ Professional Readme
✔ Professional PR

## Required Changes ♻️

- Check the comments below 👇

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 07:43 UTC, TuyishimireEric commented on style.css
> +  min-height: 70vh;
- [ ] **Good use of CSS Flexbox 🥇 🥇** However, It would be better to make small adjustments to the article's styling to follow the Figma design as much as possible 😎😎
   -  Kindly try to fix the [margins and padding](https://www.geeksforgeeks.org/css-margins-padding/) for (top, bottom, left, right) for your elements as defined in the design, I have highlighted some for your reference 🙏 
   - Kindly try to match the used colors to those of the Figma design as suggested in the project, Kindly try to focus on small details ✔✔
   - I think the button should be fitting to your container for all the projects, Kindly try to fix this issue to make your project more professional 😀
 
## your design 
![image](https://user-images.githubusercontent.com/102757126/213108364-ca5c5bc6-219a-4d06-be9d-5dd3d80681f5.png)
## Figma design 
![image](https://user-images.githubusercontent.com/102757126/213108431-c7fd6700-8caf-4b94-9836-80c1c6d7e3ef.png)

2023-01-18 07:43 UTC, TuyishimireEric commented on style.css
> +}
- [ ] I think it would be better for all your buttons to follow the button styling: **Active, Hover, and Pressed** as given in the Figma design, you may follow this [link](https://www.freecodecamp.org/news/css-button-style-hover-color-and-background/) for more info 👍 
- [ ] Kindly try to follow the styling of your buttons as much as possible to replicate the Figma design 🙏 

## Figma button design
![image](https://user-images.githubusercontent.com/102757126/213109250-169c4da2-d092-4b49-aa55-9f5a1ba45fdc.png)

2023-01-18 07:43 UTC, TuyishimireEric commented on toolbar.html
> +            <header><h1 class="about_myself">About <br> Myself</h1></header>
- [ ] I think as suggested before, it would be better to replace the ```<h1>``` tag on project titles with a ```<h2>``` or ``` other headings``` as It is generally recommended to use only one ```<h1>``` tag per webpage for the main title or heading and to use ```<h2>-<h6>``` tags for subheadings. 😎😎

2023-01-18 07:43 UTC, TuyishimireEric commented on toolbar.html
> +                    <hr>
- [ ] I think it would be better to list the technology categories ("Languages", "Frameworks" and "Skills") in a ```ul```, each of them in a ```li```, You may kindly try to use a[ multilevel lis](https://www.computerhope.com/issues/ch001703.htm)t for this, as **multilevel lists** can help to break down complex information into smaller, more manageable chunks. 
   This will make it easier for users to scan and understand the content. 😀👍

- [ ] I think it would be better also to adjust the styling of this section too, to match the Figma design 👍 👍 
   -  Kindly try to fix the [margins and padding](https://www.geeksforgeeks.org/css-margins-padding/) for (the top, bottom, left, and right) for your elements as defined in the design, I have highlighted some for your reference 🙏 
   - Kindly try to match the used colors to those of the Figma design as suggested in the project, Kindly try to focus on small details ✔✔

## Your design
![image](https://user-images.githubusercontent.com/102757126/213112099-f0208a3f-fb43-4055-b175-b68adf60d24d.png)

## Figma design
![image](https://user-images.githubusercontent.com/102757126/213112226-837fdb08-d565-4ca0-9f6e-295dfafda91c.png)

## KEEP IT UP :+1:

2023-01-18 21:09 UTC, huseyinbiyik commented on toolbar.html
> +            </div>
As the previous reviewer requested, please use the multi-level list for this area. Here is the tip for you:
```
<ul>
  <li>Languages 
      <ul>
        <li>JavaScript</li>
        <li>HTML</li>
      </ul>
  </li>
  <li> Framework</li>
</ul>
```

2023-01-19 07:52 UTC, bronnie313 commented on toolbar.html
> +                <nav class="action">
thanks i'll be more keen next time to avoid using nav element anywhere I find

2023-01-19 08:11 UTC, binhussen approved these changes
Hi @bronnie313 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 09:01 UTC, merged