add contact me section
bronnie313/Portfolio pull request #5
Opened 2023-01-21 19:25 UTC by bronnie313

added a contact me section to my portfolio page containing several input parts like 
the name part, email, and also a text area for comments or messages

2023-01-24 19:15 UTC, mukhammadrizooff requested changes
Hi @bronnie313, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- No linter errors ✔️ 
- Good implementations ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-24 19:15 UTC, mukhammadrizooff commented on style.css
> +  padding-left: 10px;
- [ ] [REQUIRED] Please change the color to correct one the `Textarea` => `color: #172b4d;` 👍🏼 

![image](https://user-images.githubusercontent.com/63915024/214386562-202f23f1-c44a-4d46-84bf-eba423cf64b0.png)

2023-01-24 19:15 UTC, mukhammadrizooff commented on style.css
> +}
- [ ] [REQUIRED] Good job so far! Please fix small mistake on `button` design 🙏🏼 

![image](https://user-images.githubusercontent.com/63915024/214386630-b7c710d4-abb3-4eac-a775-9e598c3dfa8d.png)

2023-01-24 19:15 UTC, mukhammadrizooff commented on index.html
> +            </div>
- [ ] [REQUIRED] Kindly please remove it 🙏🏼 

![image](https://user-images.githubusercontent.com/63915024/214384924-a52f00d9-1cc8-4995-82e3-b85dabc7b918.png)

2023-01-24 19:15 UTC, mukhammadrizooff commented on index.html
> +                    <li><textarea name="message" placeholder="Write your message here" class="txt_area" required></textarea></li>
- [ ] [REQUIRED] Good job so far! Please `Message` input should have `maxlength="500"` attribute 🙏🏼

2023-01-24 19:15 UTC, mukhammadrizooff commented on index.html
> +                    <li><input name="name" placeholder="name" type="text" class="text" required/></li>
- [ ] [REQUIRED] Good job so far! Please `Name` input should have `maxlength="30"` attribute 🙏🏼

2023-01-24 19:15 UTC, mukhammadrizooff commented on index.html
> +            <form action="https://formspree.io/f/{form_id}" method="post">
- [ ] [REQUIRED] Good job so far! Currently your `FORM` is not working because you did not implement [formspree service](https://formspree.io/html). Please add `{form_id}` provided from [formspree service](https://formspree.io/html) 🙏🏼  `[HINT]` Your should go the formspree website and `sign up` after that formspree give you form `ID` 👍🏼

2023-01-24 20:38 UTC, emmiiorji requested changes
Hi @bronnie313, 

# Status: Changes Required ♻️

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- Proper use of GitHub flow


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-25 04:41 UTC, bronnie313 commented
Hi Emmanuel,
You have requested me to make some changes in my contact  me form but I don't see any comments you left me after your review please reply to me so that I make the required changes before I request for my last review

2023-01-25 04:41 UTC, bronnie313 commented
Hi Emmanuel,
You have requested me to make some changes in my contact  me form but I don't see any comments you left me after your review please reply to me so that I make the required changes before I request for my last review

2023-01-25 04:53 UTC, emmiiorji commented
Hi @bronnie313

Sorry about the error. I may have missed out in submitting that while leaving my comment.

I asked that you kindly remove the border on the button as requested by the previous reviewer.

Your design:
![image](https://user-images.githubusercontent.com/20554583/214482798-dbb275fb-71ac-4dcf-93d0-6ec00ca6fcd7.png)

Figma design:
![image](https://user-images.githubusercontent.com/20554583/214482811-007d75d3-c6e9-4e1b-b7b2-b6121b018a51.png)

2023-01-25 04:55 UTC, emmiiorji commented on style.css
> +}
Hi @bronnie313

Sorry about the error. I may have missed out in submitting that while leaving my comment.

I asked that you kindly remove the border on the button as requested by the previous reviewer.

Your design:
![image](https://user-images.githubusercontent.com/20554583/214482798-dbb275fb-71ac-4dcf-93d0-6ec00ca6fcd7.png)

Figma design:
![image](https://user-images.githubusercontent.com/20554583/214482811-007d75d3-c6e9-4e1b-b7b2-b6121b018a51.png)

2023-01-25 05:10 UTC, bronnie313 commented on style.css
> +}
![button corrected already](https://user-images.githubusercontent.com/37089236/214484007-5d72742c-1fc8-49bf-96e0-bcd9a6be4763.JPG)
I changed it already as the first code review told me but if on your side it's still the same incidence please let me know so that I look out for another idea

2023-01-25 05:47 UTC, emmiiorji commented on style.css
> +}
I see that it's okay. You may resubmit and the next review will do justice. Thanks.

2023-01-25 05:57 UTC, Shedrack-Sunday approved these changes
Hi @bronnie313     👋 
 
 # STATUS: APPROVED ✔️  🍾  🥳

 Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉

 ![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)
 
 ## Highlights
✔️  Proper use of Github features 💯 
✔️  well-crafted pull request 👍 
✔️ Linters are passing 👏 
 
 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._
 

 
 Cheers and Happy coding!👏👏👏
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-25 06:21 UTC, merged